project:
  type: website
  output-dir: docs
  
website:
  title: "Cecilia Baldoni"
  favicon: shrew.png
  navbar:
    left:
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Illustrations"
        href: illustrations.qmd 
      - text: "Contact"
        href: contact.qmd
    right:
      - text: "{{< iconify fa6-brands:google-scholar >}}"
        href: https://scholar.google.com/citations?user=mxM_Py8AAAAJ&hl=en&oi=sra
      - text: "{{< iconify meteor-icons:bluesky >}}"
        href: https://bsky.app/profile/cecibaldoni.bsky.social
      - icon: instagram
        href: https://www.instagram.com/cecirockyaosta/?hl=en
      - icon: github
        href: https://github.com/cecibaldoni/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Cecilia Baldoni"

format:
  html:
    navigation:
      sidebar: false
    theme: custom.scss
    toc: true
    toc-depth: 2

editor: source
